"""lol

Revision ID: 2adf5fa420a5
Revises: fabb16d5c0dd
Create Date: 2024-03-17 13:54:02.359251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adf5fa420a5'
down_revision = 'fabb16d5c0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
