"""lol

Revision ID: 5c6698948782
Revises: f261f0744d96
Create Date: 2024-04-10 22:54:07.763887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6698948782'
down_revision = 'f261f0744d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
