"""lol

Revision ID: 81b3cb50d9d9
Revises: e5154817c8a1
Create Date: 2024-03-10 00:50:38.108146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b3cb50d9d9'
down_revision = 'e5154817c8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('faculty', sa.String(), nullable=True))
    op.add_column('test', sa.Column('course', sa.String(), nullable=True))
    op.add_column('users', sa.Column('faculty', sa.String(), nullable=True))
    op.add_column('users', sa.Column('course', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course')
    op.drop_column('users', 'faculty')
    op.drop_column('test', 'course')
    op.drop_column('test', 'faculty')
    # ### end Alembic commands ###
