"""lol

Revision ID: af58c8e854f0
Revises: eed6a36fdf2c
Create Date: 2024-05-16 22:39:15.953550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af58c8e854f0'
down_revision = 'eed6a36fdf2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'title')
    # ### end Alembic commands ###
