"""lol

Revision ID: e5154817c8a1
Revises: 
Create Date: 2024-02-25 22:03:36.243349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5154817c8a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('test', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('test', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
