"""lol

Revision ID: eed6a36fdf2c
Revises: 55340f6cdf6d
Create Date: 2024-05-16 22:23:24.023032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed6a36fdf2c'
down_revision = '55340f6cdf6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('count_point', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'count_point')
    # ### end Alembic commands ###
