"""lol

Revision ID: f261f0744d96
Revises: f96916b26ad5
Create Date: 2024-03-17 13:58:47.352038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f261f0744d96'
down_revision = 'f96916b26ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'status')
    # ### end Alembic commands ###
