"""lol

Revision ID: f96916b26ad5
Revises: 2adf5fa420a5
Create Date: 2024-03-17 13:57:49.017184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96916b26ad5'
down_revision = '2adf5fa420a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
