"""lol

Revision ID: fabb16d5c0dd
Revises: 81b3cb50d9d9
Create Date: 2024-03-16 18:14:58.827480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabb16d5c0dd'
down_revision = '81b3cb50d9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'status')
    # ### end Alembic commands ###
